AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Amazon Pinpoint IFTTT Channel.  This application will call IFTTT webhooks.  Written in Node.

Parameters:
  IFTTTWEBHOOKURL:
    Type: String
    Description: The IFTTT Webhook URL

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-pinpoint-ifttt-channel
    Description: Amazon Pinpoint IFTTT Channel.  This application will deliver Amazon Pinpoint triggered messages to IFTTT.
    Author: Amazon Pinpoint
    SpdxLicenseId: MIT-0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['amazon-pinpoint', 'pinpoint', 'custom-channel', 'IFTTT']
    HomePageUrl: https://aws.amazon.com/pinpoint
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/aws-samples/amazon-pinpoint-ifttt-channel

Resources:
  IFTTTFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ifttt/
      Handler: app.handler
      Runtime: nodejs12.x
      Timeout: 60
      Environment:
        Variables:
          IFTTTWEBHOOKURL: !Ref IFTTTWEBHOOKURL
  
  PinpointInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IFTTTFunction
      Principal: !Sub pinpoint.${AWS::Region}.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/*

Outputs:
  IFTTTFunction:
    Description: "A function invoked by an Amazon Pinpoint Campaign or Journey that will issue a POST request to IFTTT Webhook"
    Value: !GetAtt IFTTTFunction.Arn
